//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARCOeCardEntities : DbContext
    {
        public ARCOeCardEntities()
            : base("name=ARCOeCardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<CSRAssignment> CSRAssignments { get; set; }
        public virtual DbSet<CusAddress> CusAddresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<NotifyEmail> NotifyEmails { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<PrenotesUser> PrenotesUsers { get; set; }
        public virtual DbSet<PreNoteSystem> PreNoteSystems { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SiteLocation> SiteLocations { get; set; }
        public virtual DbSet<UserSiteLocation> UserSiteLocations { get; set; }
    }
}
