//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public int PreNoteId { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public System.Guid ReferenceName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual PreNoteSystem PreNoteSystem { get; set; }
    }
}
