//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSRAssignment
    {
        public int ID { get; set; }
        public string CustomerNumber { get; set; }
        public int CustomerSequence { get; set; }
        public string CustomerName { get; set; }
        public string Location { get; set; }
        public int CSR { get; set; }
        public string CSRName { get; set; }
        public int SiteLocation { get; set; }
        public string CSREmail { get; set; }
    }
}
