//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusAddress
    {
        public int ID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerSequence { get; set; }
        public string CompanyName { get; set; }
        public string CustAddr1 { get; set; }
        public string CustAddr2 { get; set; }
        public string CustAddr3 { get; set; }
        public string CustAddr4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Fax { get; set; }
        public string SalespersonName { get; set; }
        public string Type { get; set; }
        public string DateCreated { get; set; }
        public string ChangedbyID { get; set; }
    }
}
