//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string CustomerNumber { get; set; }
        public string CompanyName { get; set; }
        public string Primary_ShiptoArc { get; set; }
        public string StreetAddresses { get; set; }
        public string BilltoAddr1 { get; set; }
        public string BilltoAddr2 { get; set; }
        public string BilltoAddr3 { get; set; }
        public string BilltoAddr4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Fax { get; set; }
        public string ShiptoNAME { get; set; }
        public string ShipToNameANDStreetAddresses { get; set; }
        public string ShiptoAddr1 { get; set; }
        public string ShiptoAddr2 { get; set; }
        public string ShiptoAddr3 { get; set; }
        public string ShiptoAddr4 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToCountry { get; set; }
        public Nullable<int> ShipToSeq { get; set; }
        public string SalesPersonName { get; set; }
    }
}
