//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCO.EndPoint.eCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int ID { get; set; }
        public Nullable<int> PreNoteId { get; set; }
        public string SalesOrderNumber { get; set; }
        public string FolderPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AssignedTO { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PrenotesUser PrenotesUser { get; set; }
        public virtual PreNoteSystem PreNoteSystem { get; set; }
        public virtual SiteLocation SiteLocation { get; set; }
    }
}
